name: deployment_to_aws_lambda_function

on:
  push:
    branches:
    - main
    
jobs:
  deploy_to_Lambda:
    name: deploy_to_Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: listing files from repo
        run: ls -l
      - name: zip the code
        run : zip -r phthon.zip lambda_function.py
      - name: listing files of repo
        run: ls -l
      - name: aws cli version
        run: aws --version
      - name: code adding
        run: aws lambda update-function-code --function-name webhook --zip-file fileb://python.zip